#ifndef LIBDOCSCRIPT_VERSION_H
#define LIBDOCSCRIPT_VERSION_H

// DO NOT FORGET TO CHANGE THE VERSION NUMBER AT `CMakeLists.txt'
// IF YOU CHANGED THEM HERE !!!
// 9999 = Development Pre-release
#define LIBDOCSCRIPT_VERSION_MAJOR 0
#define LIBDOCSCRIPT_VERSION_MINOR 3
#define LIBDOCSCRIPT_VERSION_PATCH 9999

#endif