#ifndef DOCSIR_VERSION_H
#define DOCSIR_VERSION_H

// DO NOT FORGET TO CHANGE THE VERSION NUMBER AT `CMakeLists.txt'
// IF YOU CHANGED THEM HERE !!!
#define DOCSIR_VERSION_MAJOR 0
#define DOCSIR_VERSION_MINOR 3
#define DOCSIR_VERSION_PATCH 0

#endif